ui.url: http://ui:8080
auth-server: http://id:4000/id
msg.url: http://msg:5000

server:
  port: 4000
  servlet:
    context-path: /id
security:
  oauth2:
    authorization:
      check-token-access: permitAll()
#      token-key-access: permitAll()
#      check-token-access: isAuthenticated()
spring:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.security: DEBUG