server:
  port: 4000
  servlet:
    context-path: /id
#  context-path: /id
spring:
  security:
    user:
      password: password
security:
  oauth2:
    authorization:
      check-token-access: permitAll()
logging:
  level:
    org.springframework.security: DEBUG