server:
  port: 4000
  context-path: /id
security:
  user:
    password: password
  oauth2:
    authorization:
      check-token-access: permitAll()
logging:
  level:
    org.springframework.security: DEBUG